[package]
name = "informant"
version = "0.1.0"
authors = ["BlandyBrains <NothingsBland@proton.me>"]
edition = "2021"

[[bin]]
name = "informant"
path = "src/main.rs"

[dependencies]
meta = { path = "../meta" }

[dev-dependencies]